<?php
$I = new AcceptanceTester($scenario);
$I->wantTo("block a time slot");
$I->amOnPage("/index-test.php");
$I->click("Login");
$I->fillField("#staff-user_name", "admin");
$I->fillField("#staff-password", "123456789");
$I->wait(1);
$I->click("#loginBtn");
$I->click("#loginBtn");
$I->wait(2);
$I->click("System");
$I->click("Time Slots");
$I->wait(1);
$I->see("Recurring Time Slots","h1");
$I->click("span.glyphicon.glyphicon-pencil");
$I->wait(1);
$I->see("Update","button.btn.btn-primary");
$I->click("#timeslotmodel-blocking");
$I->wait(1);
$I->click("button.btn.btn-primary");
$I->wait(1);
$I->see("Yes","//tr[9]/td");
$I->wait(1);
$I->click("Update");
$I->click("#timeslotmodel-blocking");
$I->wait(1);
$I->click("button.btn.btn-primary");
$I->wait(1);
$I->see("No","//tr[9]/td");